CHANGELOG.md, logstash-patterns-core.gemspec, spec/patterns/core_spec.rb, spec/spec_helper.rb
commit a273a051d8a0ef2e44ea9ceeb4d103902127ccc0 breaks most specs while trying to solve one specific spec. The commit is reverted and the broken spec disabled. 
Also fixes the missing `pattern_path` which a temporary fix to have the spec pass for an urgent mass-publish requirement. relates to logstash-plugins/logstash-filter-grok#72
=> revert broken commit and fix pattern_path

Gemfile
currently the Gemfile doesn't allow setting up an external logstash-core, causing the plugin tests to fail.
=> fix specs by allowing the use of external logstash core

CHANGELOG.md, logstash-patterns-core.gemspec, patterns/java, spec/patterns/java_spec.rb
As the specs demonstrates `JAVAFILE` wasn't matching `RubyMethod$INVOKER$i$call.gen`.
Context: we'll be adding some missing PATTERN specs for ECS and leaving a `TODO` for discovered 'broken' behavior (to be handled later) is confusing reviewers thus I decided to target some minor (potentially breaking) changes for **4.2.0** on their own.
... to be continued
=> Fix: Java stack trace's JAVAFILE to better match generated names

CHANGELOG.md, patterns/grok-patterns, spec/patterns/core_spec.rb
Reviewing existing PRs before the ECS split - this one was attempted several times.
origin #205
=> Fix: match Information/INFORMATION in LOGLEVEL

patterns/ecs-v1/postgresql
NOTE: `POSTGRESQL` format seems outdated compared to [beat's](https://github.com/elastic/beats/blob/7.8/filebeat/module/postgresql/log/ingest/pipeline.yml#L7)
*HINT: target is **ecs-wip** branch as this should get a **final review when all patterns** are migrated*
=> Feat: ecs-ize postgresql named captures

Gemfile, lib/logstash/patterns/core.rb, patterns/ecs-v1/redis, spec/patterns/redis_spec.rb, spec/spec_helper.rb
... and shared spec helpers to ease testing in (2) different modes.
The shared helpers, when this is merged, are going to be used for other pattern migration specs ...
Did not split these into 2 PRs on purpose so that we have some spec usage in place.
*HINT: target is **ecs-wip** branch as this should get a **final review when all patterns** are migrated*
=> Feat: redis patterns ecs compatibility

CHANGELOG.md, patterns/nagios, spec/patterns/nagios_spec.rb
The `NAGIOSLOGLINE` failed to properly capture a `TIMEPERIOD TRANSITION: 24x7;-1;1` log line.
The (from/to) fields in the pattern are (due legacy reasons) named `nagios_unknown`.
a lot of potential numeric (integer) values within `NAGIOSLOGLINE` are matched simply as `DATA`,
usually not an issue except in this case where the "unknown" field is set to `-1` (to indicate a null value),
as (I am guessing) they're using the defined time-periods (such as *us_holidays* or *24x7*).
the 'not-set' value `-1` for the first field is quite common and breaks matching (due `-`).
*OT: still struggling to find a meaningful sample where these are filled with smt else than `-1;0` or `-1;1`*
=> Fix: NAGIOS TIMEPERIOD unknown (from/to) field matching

patterns/ecs-v1/mcollective, patterns/ecs-v1/mcollective-patterns, spec/patterns/mcollective_spec.rb
NOTE: MCollective is deprecated these days and (as the new spec indicates) matching seems to not have been complete.
*HINT: target is **ecs-wip** branch as this should get a **final review when all patterns** are migrated*
=> Feat: ecs-ize MCOLLECTIVE named captures

patterns/ecs-v1/squid, patterns/legacy/squid, spec/patterns/squid_spec.rb
`"1525334330.556      3 120.65.1.1 TCP_REFRESH_MISS/200 2014 GET http://www.sample.com/hellow_world.txt public-user DIRECT/www.sample.com text/plain 902351708.872"`
matching **before** and **after**:
```
"timestamp"=>"1525334330.556",
"duration"=>"3",
"client_address"=>"120.65.1.1",
"cache_result"=>"TCP_REFRESH_MISS",
"status_code"=>"200",
"bytes"=>"2014",
"request_method" => "GET",
"url" => "http://www.sample.com/hellow_world.txt",
"user"=>"public-user",
"hierarchy_code"=>"DIRECT",
"server"=>"www.sample.com",
"content_type"=>"text/plain",
```
```
"timestamp"=>"1525334330.556",
"source"=>{"ip"=>"120.65.1.1"},
"http"=>{
"request"=>{"method"=>"GET"},
"response"=>{"status_code"=>200, "body"=>{"bytes"=>2014}}
},
"destination"=>{"address"=>"www.sample.com"}, …
```
=> Feat: make SQUID3 captures ecs compliant

CHANGELOG.md, patterns/httpd, spec/patterns/httpd_spec.rb
Without this fix the following line would not match the `HTTPD_COMBINEDLOG` pattern: 
`83.149.9.216 - a.user [11/Jan/2020:23:05:27 +0100] "OPTIONS /remote.php/ HTTP/1.1" - 7908 "-" "x-client"`
due `"-"` response (after `7908 "-"`) not parsing as a number
*NOTE: there's also some more specs (which aren't relevant to the change)*
=> Fix: HTTPD access log parse failure on missing response

patterns/ecs-v1/mongodb, spec/patterns/mongodb_spec.rb
`MONGO3_LOG` is straight forward, the (legacy) `MONGO_SLOWQUERY` could use some :eyes: 
DRAFT since this will need specs for the new ECS names.
*HINT: target is **ecs-wip** branch as this should get a **final review when all patterns** are migrated*
=> Feat: ecs-ize MongoDB pattern captures

patterns/ecs-v1/bind, patterns/legacy/bind, spec/patterns/bind_spec.rb
not just a drop in replacement e.g. `querytype` field is parsed further,
detailed changes should be visible from the spec, but also : 
`"query" => ["test.example.com", "test.example.com"], "querytype" => "A +E(0)K"` previously
`"dns" => { "question" => { "name" => "test.example.com", "type" => 'A', "class" => 'IN' },` 
`"bind" => { "log" => { "question" => { "flags" => '+E(0)K' }`ecs-ified
*HINT: quite a hustle to identify a real-world log this was matching, as there were no previous tests, I am planning to follow-up at least with at least minor compatible updates. There's changes in log format in pretty much every minor Bind 9.x version.*
=> Feat: ecs-ize BIND9 query log captures

patterns/legacy/exim, spec/patterns/exim_spec.rb
another day another grok pattern story: this time the *exim* (mail server) patterns seem incomplete.
there seems to be partial sub-patterns and experiments with excluding specific messages which are hard to follow.
in their current (partial) form it's pretty much impossible to even come up with meaningful tests (for ECS).
the proposal here tries to establish a useful (but still minimal) `EXIM` line - for matching "mail arrival" logs (**<=**).
hoping to build exim **ECS support on top of this**.
NOTES:
- changes to existing patterns are backwards compatible
- all presented specs are passing
- there's a mix of %{:grok} and \<regexp\> style named captures
due the effort to eliminate introducing more `EXIM_xxx` (legacy) names
- other options include only having `EXIM` definition for tests (in …
=> (legacy) EXIM base-line for ECS-ification

patterns/ecs-v1/httpd, spec/patterns/httpd_spec.rb
Beats already has support for [matching](https://github.com/elastic/beats/blob/v7.8.0/filebeat/module/apache/access/ingest/pipeline.yml) */var/log/httpd/access.log* where they're using the `apache.access` prefix for custom fields. 
~~There's no beats support for parsing the Apache error log, have tried using the same prefix convention which turns out a bit confusing e.g. `apache.error.error_code` as noted on the comments inline.~~
Also, yet again, LS' matching patterns seem outdated and could end up matching imperfectly (as seen in the demonstrated new spec). But this is out-of-scope here.
prerequisite: #282
=> Feat: ecs-ize httpd patterns

CHANGELOG.md, patterns/grok-patterns, spec/patterns/core_spec.rb
Using `PATH` and namely it's sub-pattern `UNIXPATH` can lead to DoS (due regular expression back-tracking).
Sample one line reproducer (pattern is the original expanded `UNIXPATH`):
`ruby -e '/(\/([\w_%!$@:.,+~-]+|\\\\.)*)+ /.match "/opt/abcdef/1/.22/3:3+3/foo@BAR/X-Y+Z/~Sample_l_&^_c b"'`
... the important part is the non-matching `&^` sequence at the end.
Currently `UNIXPATH` does not handle unicode chars (separate issue), this issue (100% CPU) was discovered with non-ascii chars at the end: `/home/eaeaea/data/import/Sample_xyz_lé_é_c b`
~~Also to be noted that the pattern does not interrupt properly, using a timeout, thus there isn't a good work-around except not using or redefining `PATH/UNIXPATH`.~~
resolves https://github.com/logstash-plugins/logstash-patterns-core/issues/159
=> Fix: UNIXPATH to avoid DoS on long paths with unmatching chars

patterns/ecs-v1/nagios, spec/patterns/nagios_spec.rb
Here I have mostly struggled with getting the naming right - too much "state"/"type" use in Nagios terminology.
Have decided to name "state status" as `status` (previously `nagios_state`) and state type as `state_type` (legacy name `nagios_statetype`)
The structure is rather flat to mirror Nagios (introducing `state: { type: "..." } ` would be an option but the terminology would not follow that well). It's a bit of a compromise, sample capture:
p.s. Some of the names were incorrect those have been fixed and specs should clearly reflect the change.
`[1427925600] CURRENT HOST STATE: nagioshost;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 2.24 ms`
```
"nagios_epoch"=>"1427925600", 
"nagios_type"=>"CURRENT HOST STATE", 
"nagios_hostname"=>"nagioshost", 
"nagios_state"=>"UP", …
```
=> Feat: make NAGIOSLOGLINE captures ECS compliant

CHANGELOG.md, patterns/grok-patterns, spec/patterns/core_spec.rb
`WINPATH` matches paths containin non-ascii chars but `UNIXPATH` does not, which makes `PATH` inconsistent.
e.g. `/var/vtaky/ďateľ/čierny` is a valid path name on Linux and should be matched ... 
The issue was discovered while bumping into #159 a longer path had chars with diacritics towards the end (such as `/home/eaeaea/data/import/Sample_xyz_lé_é_c b` from #292), this not only did not match but actually lead to a slow ingestion process as all of these entries needed to abort the extensive back-tracking with a grok timeout.
(follow-up on https://github.com/logstash-plugins/logstash-patterns-core/pull/292)
=> Feat: allow UNIXPATH to match non-ascii chars

patterns/ecs-v1/junos, spec/patterns/junos_spec.rb
These should be fairly straight-forward - Beats has a [Juniper module](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-juniper.html).
There were no existing specs but according to Juniper KB these match unstructured SRX gateway logs.
NOTE: Beats only supports [structured logs](https://github.com/elastic/beats/blob/v7.10.1/x-pack/filebeat/module/juniper/srx/test/flow.log#L1) while here LS is aimed at parsing unstructured log lines.
For better interoperability we follow the `juniper.srx` prefix naming for custom fields established by Beats.
=> Feat: ECS compliant Juniper (SRX) RT_FLOW captures

patterns/ecs-v1/java, spec/patterns/core_spec.rb, spec/patterns/java_spec.rb
should be straightforward except 2 hiccups:
- Java class-name capture naming (no ECS convention really)
- `message` sub-part wasn't being matched (appended) to `message` but rather to `logmessage`
which I believe is good but we did not yet decide whether that's a convention to follow
(in which case it should be followed for all ecs-ized patterns -> namespacing sub-message part)
---
resolves https://github.com/logstash-plugins/logstash-patterns-core/issues/123 closing https://github.com/logstash-plugins/logstash-patterns-core/pull/244
=> Feat: make java patterns match in an ecs compatible way

.ci/setup.sh, Gemfile
... after https://github.com/logstash-plugins/logstash-filter-grok/pull/162 (logstash-filter-grok is released)
=> Build: revert the need to use a git source

CHANGELOG.md, logstash-patterns-core.gemspec, patterns/ecs-v1/firewalls, patterns/ecs-v1/linux-syslog, spec/patterns/firewalls_spec.rb, spec/patterns/netscreen_spec.rb, spec/patterns/syslog_spec.rb
a follow-up on https://github.com/logstash-plugins/logstash-patterns-core/pull/297
- for `SYSLOG5424PRI` we clearly want `log.syslog.priority`
- same for `CISCO_TAGGED_SYSLOG`
this field slipped through ECS-ification (no proper use-case with the specific pattern files e.g. `CISCOFW104001`)
we clearly missed ECS-ifing the `ciscotag` field name (as `cisco.asa.tag`)
=> Fix: incorrect syslog (priority) field name

spec/patterns/core_spec.rb, spec/patterns/redis_spec.rb
somehow specs for `REDISMONLOG` were missing in ECS mode.
also some of the specs adjusted here were run in default mode which on LS 8.x is ECS on by default 
-> yet the specs assumed legacy behavior 
:green_circle: CI
=> Test: fix and add ECS compatibility specs
